name: Build Binaries (Clean)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 0.4.37)'
        required: false
        type: string

permissions:
  contents: read
  actions: write

jobs:
  build-macos:
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - arch: x64
            runner: macos-13  # Intel runner
          - arch: arm64
            runner: macos-latest  # Apple Silicon runner
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Get version
      id: version
      run: |
        if [ -n "${{ github.event.inputs.version }}" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=$(uv run python -c "from folder2md4llms.__version__ import __version__; print(__version__)")
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"

    - name: Install dependencies
      run: |
        uv sync --group dev --extra build --extra tiktoken

    - name: Install platform-specific dependencies
      run: |
        # Install libmagic for macOS
        brew install libmagic

    - name: Prepare PyInstaller spec for architecture
      run: |
        # Create architecture-specific spec file
        cp folder2md.spec folder2md-${{ matrix.arch }}.spec

        # Update binary name to include architecture
        sed -i '' 's/name="folder2md"/name="folder2md-macos-${{ matrix.arch }}"/' folder2md-${{ matrix.arch }}.spec

    - name: Build binary with PyInstaller
      run: |
        echo "::group::Building binary for ${{ matrix.arch }}"
        uv run pyinstaller folder2md-${{ matrix.arch }}.spec --clean --noconfirm
        echo "::endgroup::"

    - name: Verify binary
      run: |
        echo "::group::Verifying binary"

        BINARY_PATH="dist/folder2md-macos-${{ matrix.arch }}"

        if [ ! -f "$BINARY_PATH" ]; then
          echo "❌ Binary not found at $BINARY_PATH"
          ls -la dist/
          exit 1
        fi

        echo "✅ Binary found: $BINARY_PATH"
        ls -lh "$BINARY_PATH"

        # Check architecture
        file "$BINARY_PATH"

        # Test basic functionality (native build)
        echo "Testing binary functionality..."
        "$BINARY_PATH" --version
        "$BINARY_PATH" --help > /dev/null

        echo "::endgroup::"

    - name: Generate checksums
      run: |
        echo "::group::Generating checksums"

        cd dist
        BINARY_NAME="folder2md-macos-${{ matrix.arch }}"

        # Generate SHA256 checksum
        shasum -a 256 "$BINARY_NAME" > "${BINARY_NAME}.sha256"

        # Generate MD5 checksum for additional verification
        md5 "$BINARY_NAME" > "${BINARY_NAME}.md5"

        echo "Generated checksums:"
        cat "${BINARY_NAME}.sha256"
        cat "${BINARY_NAME}.md5"

        echo "::endgroup::"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: folder2md-macos-${{ matrix.arch }}
        path: |
          dist/folder2md-macos-${{ matrix.arch }}
          dist/folder2md-macos-${{ matrix.arch }}.sha256
          dist/folder2md-macos-${{ matrix.arch }}.md5
        retention-days: 30

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 60
    strategy:
      matrix:
        arch: [x64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Get version
      id: version
      run: |
        if ($env:GITHUB_EVENT_INPUTS_VERSION) {
          $VERSION = $env:GITHUB_EVENT_INPUTS_VERSION
        } else {
          $VERSION = uv run python -c "from folder2md4llms.__version__ import __version__; print(__version__)"
        }
        echo "version=$VERSION" >> $env:GITHUB_OUTPUT
        Write-Host "Building version: $VERSION"
      shell: pwsh

    - name: Install dependencies
      run: |
        uv sync --group dev --extra build --extra tiktoken
      shell: pwsh

    - name: Prepare PyInstaller spec for Windows
      run: |
        # Create Windows-specific spec file
        Copy-Item folder2md.spec folder2md-windows-${{ matrix.arch }}.spec

        # Update binary name to include platform and architecture
        (Get-Content folder2md-windows-${{ matrix.arch }}.spec) -replace 'name="folder2md"', 'name="folder2md-windows-${{ matrix.arch }}"' | Set-Content folder2md-windows-${{ matrix.arch }}.spec
      shell: pwsh

    - name: Build binary with PyInstaller
      run: |
        Write-Host "::group::Building Windows binary for ${{ matrix.arch }}"

        # Build the binary
        uv run pyinstaller folder2md-windows-${{ matrix.arch }}.spec --clean --noconfirm

        Write-Host "::endgroup::"
      shell: pwsh

    - name: Verify binary
      run: |
        Write-Host "::group::Verifying Windows binary"

        $BINARY_PATH = "dist/folder2md-windows-${{ matrix.arch }}.exe"

        if (-not (Test-Path $BINARY_PATH)) {
          Write-Host "❌ Binary not found at $BINARY_PATH"
          Get-ChildItem dist/
          exit 1
        }

        Write-Host "✅ Binary found: $BINARY_PATH"
        Get-ChildItem $BINARY_PATH | Format-List

        # Test basic functionality
        Write-Host "Testing binary functionality..."
        & $BINARY_PATH --version
        & $BINARY_PATH --help | Out-Null

        Write-Host "::endgroup::"
      shell: pwsh

    - name: Generate checksums
      run: |
        Write-Host "::group::Generating checksums"

        Set-Location dist
        $BINARY_NAME = "folder2md-windows-${{ matrix.arch }}.exe"

        # Generate SHA256 checksum
        $sha256 = (Get-FileHash $BINARY_NAME -Algorithm SHA256).Hash.ToLower()
        "$sha256  $BINARY_NAME" | Out-File -FilePath "${BINARY_NAME}.sha256" -Encoding ascii

        # Generate MD5 checksum for additional verification
        $md5 = (Get-FileHash $BINARY_NAME -Algorithm MD5).Hash.ToLower()
        "$md5  $BINARY_NAME" | Out-File -FilePath "${BINARY_NAME}.md5" -Encoding ascii

        Write-Host "Generated checksums:"
        Get-Content "${BINARY_NAME}.sha256"
        Get-Content "${BINARY_NAME}.md5"

        Write-Host "::endgroup::"
      shell: pwsh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: folder2md-windows-${{ matrix.arch }}
        path: |
          dist/folder2md-windows-${{ matrix.arch }}.exe
          dist/folder2md-windows-${{ matrix.arch }}.exe.sha256
          dist/folder2md-windows-${{ matrix.arch }}.exe.md5
        retention-days: 30
