name: Release to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for hatch-vcs
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --dev
        uv pip install hatch
    
    - name: Run tests
      run: uv run pytest
    
    - name: Build package
      run: uv run hatch build
    
    - name: Check version matches tag
      run: |
        VERSION=$(uv run hatch version)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "Package version: $VERSION"
        echo "Tag version: $TAG_VERSION"
        echo "Git describe: $(git describe --tags --always)"
        echo "Git status: $(git status --porcelain)"
        echo "Git log --oneline -3: $(git log --oneline -3)"
        # Remove the __about__.py file to force a clean state
        rm -f src/folder2md4llms/__about__.py
        git checkout HEAD -- src/folder2md4llms/__about__.py 2>/dev/null || true
        echo "After cleanup - Package version: $(uv run hatch version)"
        VERSION=$(uv run hatch version)
        if [ "$VERSION" != "$TAG_VERSION" ]; then
          echo "Version mismatch: package=$VERSION, tag=$TAG_VERSION"
          exit 1
        fi
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true